
all: p1 p2 p3 p4 p5 p6 p7 p8

clean:
 	rm -f p1 p2 p3 p4 p5 p6 p7 p8

p1: p1.c
	gcc -g -o p1 p1.c -Wall

p2: p2.c
	gcc -g -o p2 p2.c -Wall

p3: p3.c
	gcc -g -o p3 p3.c -Wall

p4: p4.c
	gcc -g -o p4 p4.c -Wall

p5: p5.c
	gcc -g -o p5 p5.c -Wall

p6: p6.c
	gcc -g -o p6 p6.c -Wall

p7: p7.c
	gcc -g -o p7 p7.c -Wall

p8: p8.c
	gcc -g -o p8 p8.c -Wall