
all: p1 p2 p3 p4 null

clean:
	rm -rf p1 p2 p3 p4 null *.dSYM

p1: p1.c
	gcc -g -o p1 p1.c -Wall

p2: p2.c
	gcc -g -o p2 p2.c -Wall

p3: p3.c
	gcc -g -o p3 p3.c -Wall

p4: p4.c
	gcc -g -o p4 p4.c -Wall

null: null.c
	gcc -g -o null null.c -Wall

